DROP TABLE IF EXISTS EMAIL_CONFIG CASCADE;

DROP SEQUENCE IF EXISTS EMAIL_CONFIG_SEQUENCE;

CREATE SEQUENCE EMAIL_CONFIG_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE EMAIL_CONFIG
(
    EMAIL_ID                  INTEGER NOT NULL,
    TYPE                      VARCHAR(255) NOT NULL,
    EMAIL_FROM                VARCHAR(255) NOT NULL,
    EMAIL_TO                  VARCHAR(255) NULL,
    SUBJECT                   VARCHAR(255) NOT NULL,
    MESSAGE                   VARCHAR(5000) NOT NULL,
    PRIMARY KEY (EMAIL_ID)
);

