DROP TABLE IF EXISTS LANGUAGES CASCADE;
DROP TABLE IF EXISTS EMAIL_TYPES CASCADE;
DROP TABLE IF EXISTS EMAIL_CONFIGS CASCADE;

DROP SEQUENCE IF EXISTS LANGUAGES_SEQUENCE;
DROP SEQUENCE IF EXISTS EMAIL_TYPES_SEQUENCE;
DROP SEQUENCE IF EXISTS EMAIL_CONFIGS_SEQUENCE;

CREATE SEQUENCE LANGUAGES_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMAIL_TYPES_SEQUENCE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EMAIL_CONFIGS_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE LANGUAGES
(
    LANGUAGE_ID             INTEGER NOT NULL,
    LANGUAGE_CODE           VARCHAR(10) NOT NULL,
    LANGUAGE_NAME           VARCHAR(10) NOT NULL,
    PRIMARY KEY (LANGUAGE_ID)
);

CREATE TABLE EMAIL_TYPES
(
    EMAIL_TYPE_ID             INTEGER NOT NULL,
    EMAIL_TYPE                VARCHAR(255) NOT NULL,
    PRIMARY KEY (EMAIL_TYPE_ID)
);

CREATE TABLE EMAIL_CONFIGS
(
    EMAIL_CFG_ID              INTEGER NOT NULL,
    EMAIL_TYPE_ID             INTEGER NOT NULL,
    LANGUAGE_ID               INTEGER NOT NULL,
    EMAIL_FROM                VARCHAR(255) NOT NULL,
    EMAIL_TO                  VARCHAR(255) NULL,
    SUBJECT                   VARCHAR(255) NOT NULL,
    FILE_PATH                 VARCHAR(255) NOT NULL,
    PRIMARY KEY (EMAIL_CFG_ID)
);


CREATE INDEX IDX_EMAIL_CONFIGS_01
    ON EMAIL_CONFIGS (EMAIL_CFG_ID, EMAIL_TYPE_ID, LANGUAGE_ID);

CREATE INDEX IDX_EMAIL_CONFIGS_02
    ON EMAIL_CONFIGS (EMAIL_TYPE_ID, LANGUAGE_ID);

ALTER TABLE EMAIL_CONFIGS
    ADD CONSTRAINT FK_EMAIL_TYPE
    FOREIGN KEY (EMAIL_TYPE_ID)
    REFERENCES EMAIL_TYPES (EMAIL_TYPE_ID);

ALTER TABLE EMAIL_CONFIGS
    ADD CONSTRAINT FK_LANGUAGE
    FOREIGN KEY (LANGUAGE_ID)
    REFERENCES LANGUAGES (LANGUAGE_ID);